name: MobScaler
main: com.spiny.mobscaler.main.MobScaler
version: 3.0
commands:
  mobscaler:
    aliases: ["mob","scaler"]
    description: "Parent command for mobscaler."
permissions:
  mobscaler.set:
    default: op
  mobscaler.set.other:
    default: op
  mobscaler.freeze:
    default: op
  mobscaler.freeze.other:
    default: op
  mobscaler.info:
    default: op
  mobscaler.info.other:
    default: op
  mobscaler.save:
    default: op
  mobscaler.reload:
    default: op
  